### PR TITLE
`dev` branch

### PR DESCRIPTION
**Pull request by Nate-Wessel**
draft PR to better see file diffs

### CODE REVIEW

**Comment by Nate-Wessel** [comment]
dev build builds, but page load fails seemingly depending on a server endpoint that no longer exists

**Comment by Nate-Wessel** [comment]
@qiwenliu910, @Accelsnow, @Altair59, @KenSB:
This is perhaps a longshot, so many years later, but do any of you recall what the major differences are between the `dev` and `deploy` branches of this repo? `dev` is very far along here... is it meant to be production-ready?

**Comment by qiwenliu910** [comment]
@Nate-Wessel Sorry we worked on this project very long time ago. I vaguely remember the deploy branch is meant for a certain deliverable at school and the dev branch is the up-to-date one.

I am looking at the **original repo handed over to Raphael**. Looking at this repo, it seems like you guy have some updates, so I am not quite sure. Sorry : (

**Comment by Nate-Wessel** [comment]
@qiwenliu910 that's actually very helpful! Thanks!

Is this the original? https://github.com/qiwenliu910/Toronto-Big-Data-Innovation-Team

**Comment by qiwenliu910** [comment]
Yes! : )

**Comment by Accelsnow** [comment]
@Nate-Wessel  Hi Nate. I was managing the backend/frontend depolyment details so I can answer your questions here. We did this project as part of UofT's software engineering course, and it had a mandatory test/deploy component. As a result, we set up 2 amazon AWS servers, one for testing purpose, which the dev branch uses, and one for deployment purpose, which the deploy branch uses. Both branches would require the corresponding server to be up and running to function, as the server addresses are hardcoded in the frontend [here](https://github.com/Accelsnow/team-project-22-toronto-big-data-innovation-team/blob/dev/frontend/src/actions/actions.js), and in the backend [here](https://github.com/Accelsnow/team-project-22-toronto-big-data-innovation-team/blob/dev/backend/config.py) (there is a list of backend environment variables we used to configure the servers).

A brief explanation of how the pipeline originally works is as follows:
- There is one and only one database server containing the sample data. I hosted on my own private server. This is the DATABASE_URL environment variable, accessed via SECRET_KEY. There are also some other environment variables used as configurations.
- The backend python API server is hosted on two amazon servers (dev server and deploy server). They provide interfaces for fetching data from the database.
- The frontend NodeJS connects to the corresponding backend API server and gets the map data required for drawing.

Let me know if you have any question :)

**Comment by Nate-Wessel** [comment]
@Accelsnow Thanks Adrian for the detailed reply. That's really helpful information! It took a bit of work to reconfigure some things for our internal deployment but this is up and running smoothly once again. I was pleasantly surprised in particular how easy it was to set up a local dev environment. 

Anyway, thanks for the reply and for y'all's work on this project!

**Pull request merged**
